// Auto-generated types from Sanity schemas
// DO NOT EDIT THIS FILE MANUALLY - It will be overwritten
// Generated at: 2025-12-18T14:34:05.807Z
// Run: npm run typegen to regenerate

export interface Slug {
  _type: 'slug'
  current: string
}

export interface ImageAsset {
  _type: 'image'
  asset: {
    _type: 'reference'
    _ref: string
  }
  hotspot?: {
    x: number
    y: number
    height: number
    width: number
  }
  crop?: {
    top: number
    bottom: number
    left: number
    right: number
  }
}

export interface Reference {
  _type: 'reference'
  _ref: string
  _weak?: boolean
}

// Tenant (Store) - Generated from sanity/schemaTypes/tenant.ts
export interface Tenant {
  _id: string
  _type: 'tenant'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  domain?: string
  description?: string
  logo?: ImageAsset
}

// Product - Generated from sanity/schemaTypes/product.ts
export interface Product {
  _id: string
  _type: 'product'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  shop?: Reference
  shopName?: string
  description?: string
  price: number
  images?: ImageAsset[]
  imageUrl?: string
  category?: string
  inStock?: boolean
  stockQuantity?: number
}

// Category - Generated from sanity/schemaTypes/category.ts
export interface Category {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  description?: string
  image?: ImageAsset
}

// Union type for all document types
export type SanityDocument = Tenant | Product | Category

// Query result types
export type ProductsQueryResult = Product[]
export type TenantsQueryResult = Tenant[]
export type CategoriesQueryResult = Category[]

// Helper type for GROQ queries
export type QueryResult<T> = T extends Product 
  ? Product[] 
  : T extends Tenant 
  ? Tenant[] 
  : T extends Category 
  ? Category[] 
  : never
