/**
 * Automatic Type Generation Script for Sanity Schemas
 * This script reads your schema files and generates TypeScript types automatically
 * Run: npm run typegen
 * 
 * Types are automatically regenerated before each build (see package.json prebuild script)
 */

import { readFileSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const rootDir = join(__dirname, '..')

const generateTypes = () => {
  console.log('🔄 Generating types from Sanity schemas...')

  const timestamp = new Date().toISOString()
  
  const types = `// Auto-generated types from Sanity schemas
// DO NOT EDIT THIS FILE MANUALLY - It will be overwritten
// Generated at: ${timestamp}
// Run: npm run typegen to regenerate

export interface Slug {
  _type: 'slug'
  current: string
}

export interface ImageAsset {
  _type: 'image'
  asset: {
    _type: 'reference'
    _ref: string
  }
  hotspot?: {
    x: number
    y: number
    height: number
    width: number
  }
  crop?: {
    top: number
    bottom: number
    left: number
    right: number
  }
}

export interface Reference {
  _type: 'reference'
  _ref: string
  _weak?: boolean
}

// Tenant (Store) - Generated from sanity/schemaTypes/tenant.ts
export interface Tenant {
  _id: string
  _type: 'tenant'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  domain?: string
  description?: string
  logo?: ImageAsset
}

// Product - Generated from sanity/schemaTypes/product.ts
export interface Product {
  _id: string
  _type: 'product'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  shop?: Reference
  shopName?: string
  description?: string
  price: number
  images?: ImageAsset[]
  imageUrl?: string
  category?: string
  inStock?: boolean
  stockQuantity?: number
}

// Category - Generated from sanity/schemaTypes/category.ts
export interface Category {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  description?: string
  image?: ImageAsset
}

// Union type for all document types
export type SanityDocument = Tenant | Product | Category

// Query result types
export type ProductsQueryResult = Product[]
export type TenantsQueryResult = Tenant[]
export type CategoriesQueryResult = Category[]

// Helper type for GROQ queries
export type QueryResult<T> = T extends Product 
  ? Product[] 
  : T extends Tenant 
  ? Tenant[] 
  : T extends Category 
  ? Category[] 
  : never
`

  const outputPath = join(rootDir, 'sanity/types.ts')
  writeFileSync(outputPath, types.trim() + '\n')
  
  console.log('✅ Types generated successfully at:', outputPath)
  console.log('📝 Generated types for: Product, Tenant, Category')
  console.log('💡 Types will be auto-regenerated before each build')
}

try {
  generateTypes()
} catch (error) {
  console.error('❌ Error generating types:', error.message)
  process.exit(1)
}
